name: "🚀 Token Support Request"
description: Request a new token to be supported in our bridge
labels: ["pending triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this token support request!
  - type: input
    id: token-name
    attributes:
      label: Token Name
      description: Full name of the token. For BRC20 or Runes assets, ensure they are deployed on the Bitcoin Mainnet.
      placeholder: e.g., ordi, DOGS
    validations:
      required: true
  - type: input
    id: token-link
    attributes:
      label: Token Link
      description: Provide the token's explorer URL. For BRC20 or Runes, provide a Unisat link.
      placeholder: e.g. https://unisat.io/brc20/ordi
    validations:
      required: true
  - type: input
    id: token-icon
    attributes:
      label: Token Icon
      description: Icon link of the token
      placeholder: e.g., https://ordiscan.com/brc20/ORDI.png
    validations:
      required: false
  - type: dropdown
    id: token-type
    attributes:
      label: Token Type
      description: Select the type of token
      options:
        - BRC-20
        - RUNES
        - ERC-20
        - xUDT
        - Other
    validations:
      required: true
  - type: checkboxes
    id: service
    attributes:
      label: Requested Services
      description: Which services should support this token?
      options:
        - label: Bool Bridge
        - label: Fractal Bridge
        - label: B² Bridge
        - label: CKB Bridge
  - type: textarea
    id: description
    attributes:
      label: Additional Details
      description: Provide more information, including which chains you want to bridge the assets between, etc.
      placeholder: Enter additional details here
  - type: checkboxes
    id: required-info
    attributes:
      label: Final Checks
      description: Before submitting, please ensure you have done the following
      options:
        - label: I have checked existing [issues](https://github.com/boolnetwork/bool-bridge-feedback/issues) for similar requests.
          required: true
